
model_name: Xception # #MobileNetV2 #  # ResNet50V2, ResNet50V2, MobileNetV2
train:
  batch_size: 64
  epochs: 100
  learning_rate: 0.0003

model_params:
  l2_penalty: 0.00002
  input_shape: [96,96,7]
  dropout: 0.4
